version: '2'
services:
  worker:
    build: .
    container_name: worker
    links:
      - rabbitmq
      - redis
    environment:
      - C_FORCE_ROOT=true
  publisher:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: publisher
    links:
      - rabbitmq
      - redis
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - '8080:15672'
  redis:
    image: redis:3-alpine
    container_name: redis